def cashflow(stock):
    return {
        'Free Cash Flow': [[
            stock.cashFlow.quarter(2020, "Q2").get("Free Cash Flow"),
            stock.cashFlow.quarter(2020, "Q1").get("Free Cash Flow"),
            stock.cashFlow.year(2019).get("Free Cash Flow"),
            stock.cashFlow.year(2018).get("Free Cash Flow"),
            stock.cashFlow.year(2017).get("Free Cash Flow"),
            stock.cashFlow.year(2016).get("Free Cash Flow"),
        ], "money"],
        'Acquisitions': [[
            stock.cashFlow.quarter(2020, "Q2").get("Acquisitions"),
            stock.cashFlow.quarter(2020, "Q1").get("Acquisitions"),
            stock.cashFlow.year(2019).get("Acquisitions"),
            stock.cashFlow.year(2018).get("Acquisitions"),
            stock.cashFlow.year(2017).get("Acquisitions"),
            stock.cashFlow.year(2016).get("Acquisitions"),
        ], "money"],
        'Stock Buyback': [[
            stock.cashFlow.quarter(2020, "Q2").get("Stock Buyback"),
            stock.cashFlow.quarter(2020, "Q1").get("Stock Buyback"),
            stock.cashFlow.year(2019).get("Stock Buyback"),
            stock.cashFlow.year(2018).get("Stock Buyback"),
            stock.cashFlow.year(2017).get("Stock Buyback"),
            stock.cashFlow.year(2016).get("Stock Buyback"),
        ], "money"],
        'Net Change in Cash': [[
            stock.cashFlow.quarter(2020, "Q2").get("Net Change in Cash"),
            stock.cashFlow.quarter(2020, "Q1").get("Net Change in Cash"),
            stock.cashFlow.year(2019).get("Net Change in Cash"),
            stock.cashFlow.year(2018).get("Net Change in Cash"),
            stock.cashFlow.year(2017).get("Net Change in Cash"),
            stock.cashFlow.year(2016).get("Net Change in Cash"),
        ], "money"],
        'Operating Cash Flow': [[
            stock.cashFlow.quarter(2020, "Q2").get("Operating Cash Flow"),
            stock.cashFlow.quarter(2020, "Q1").get("Operating Cash Flow"),
            stock.cashFlow.year(2019).get("Operating Cash Flow"),
            stock.cashFlow.year(2018).get("Operating Cash Flow"),
            stock.cashFlow.year(2017).get("Operating Cash Flow"),
            stock.cashFlow.year(2016).get("Operating Cash Flow"),
        ], "money"],
        'Investing Cash Flow': [[
            stock.cashFlow.quarter(2020, "Q2").get("Investing Cash Flow"),
            stock.cashFlow.quarter(2020, "Q1").get("Investing Cash Flow"),
            stock.cashFlow.year(2019).get("Investing Cash Flow"),
            stock.cashFlow.year(2018).get("Investing Cash Flow"),
            stock.cashFlow.year(2017).get("Investing Cash Flow"),
            stock.cashFlow.year(2016).get("Investing Cash Flow"),
        ], "money"],
        'Financing Cash Flow': [[
            stock.cashFlow.quarter(2020, "Q2").get("Financing Cash Flow"),
            stock.cashFlow.quarter(2020, "Q1").get("Financing Cash Flow"),
            stock.cashFlow.year(2019).get("Financing Cash Flow"),
            stock.cashFlow.year(2018).get("Financing Cash Flow"),
            stock.cashFlow.year(2017).get("Financing Cash Flow"),
            stock.cashFlow.year(2016).get("Financing Cash Flow"),
        ], "money"],
    }
