def income(stock):
    return {
        'Interest Expense': [[
            stock.income.quarter(2020, "Q2").get("Interest Expense"),
            stock.income.quarter(2020, "Q1").get("Interest Expense"),
            stock.income.year(2019).get("Interest Expense"),
            stock.income.year(2018).get("Interest Expense"),
            stock.income.year(2017).get("Interest Expense"),
            stock.income.year(2016).get("Interest Expense"),
        ], "ratio"],
        'Total Revenue': [[
            stock.income.quarter(2020, "Q2").get("Total Revenue"),
            stock.income.quarter(2020, "Q1").get("Total Revenue"),
            stock.income.year(2019).get("Total Revenue"),
            stock.income.year(2018).get("Total Revenue"),
            stock.income.year(2017).get("Total Revenue"),
            stock.income.year(2016).get("Total Revenue"),
        ], "money"],
        'EBITDA': [[
            stock.income.quarter(2020, "Q2").get("EBITDA"),
            stock.income.quarter(2020, "Q1").get("EBITDA"),
            stock.income.year(2019).get("EBITDA"),
            stock.income.year(2018).get("EBITDA"),
            stock.income.year(2017).get("EBITDA"),
            stock.income.year(2016).get("EBITDA"),
        ], "money"],
        'Net Income': [[
            stock.income.quarter(2020, "Q2").get("Net Income"),
            stock.income.quarter(2020, "Q1").get("Net Income"),
            stock.income.year(2019).get("Net Income"),
            stock.income.year(2018).get("Net Income"),
            stock.income.year(2017).get("Net Income"),
            stock.income.year(2016).get("Net Income"),
        ], "money"],
        'Net Income Ratio': [[
            stock.income.quarter(2020, "Q2").get("Net Income Ratio"),
            stock.income.quarter(2020, "Q1").get("Net Income Ratio"),
            stock.income.year(2019).get("Net Income Ratio"),
            stock.income.year(2018).get("Net Income Ratio"),
            stock.income.year(2017).get("Net Income Ratio"),
            stock.income.year(2016).get("Net Income Ratio"),
        ], "ratio"],
        'Gross Profit': [[
            stock.income.quarter(2020, "Q2").get("Gross Profit"),
            stock.income.quarter(2020, "Q1").get("Gross Profit"),
            stock.income.year(2019).get("Gross Profit"),
            stock.income.year(2018).get("Gross Profit"),
            stock.income.year(2017).get("Gross Profit"),
            stock.income.year(2016).get("Gross Profit"),
        ], "money"],
        'Gross Profit Ratio': [[
            stock.income.quarter(2020, "Q2").get("Gross Profit Ratio"),
            stock.income.quarter(2020, "Q1").get("Gross Profit Ratio"),
            stock.income.year(2019).get("Gross Profit Ratio"),
            stock.income.year(2018).get("Gross Profit Ratio"),
            stock.income.year(2017).get("Gross Profit Ratio"),
            stock.income.year(2016).get("Gross Profit Ratio"),
        ], "ratio"],
        'Operating Income': [[
            stock.income.quarter(2020, "Q2").get("Operating Income"),
            stock.income.quarter(2020, "Q1").get("Operating Income"),
            stock.income.year(2019).get("Operating Income"),
            stock.income.year(2018).get("Operating Income"),
            stock.income.year(2017).get("Operating Income"),
            stock.income.year(2016).get("Operating Income"),
        ], "money"],
        'Operating Income Ratio': [[
            stock.income.quarter(2020, "Q2").get("Operating Income Ratio"),
            stock.income.quarter(2020, "Q1").get("Operating Income Ratio"),
            stock.income.year(2019).get("Operating Income Ratio"),
            stock.income.year(2018).get("Operating Income Ratio"),
            stock.income.year(2017).get("Operating Income Ratio"),
            stock.income.year(2016).get("Operating Income Ratio"),
        ], "ratio"],
            'EPS': [[
            stock.income.quarter(2020, "Q2").get("EPS"),
            stock.income.quarter(2020, "Q1").get("EPS"),
            stock.income.year(2019).get("EPS"),
            stock.income.year(2018).get("EPS"),
            stock.income.year(2017).get("EPS"),
            stock.income.year(2016).get("EPS"),
        ], "money"],
    }
