def ratios(stock):
    return {
        'Gross Profit Margin': [[
            stock.ratios.quarter(2020, "Q2").get("Gross Profit Margin"),
            stock.ratios.quarter(2020, "Q1").get("Gross Profit Margin"),
            stock.ratios.year(2019).get("Gross Profit Margin"),
            stock.ratios.year(2018).get("Gross Profit Margin"),
            stock.ratios.year(2017).get("Gross Profit Margin"),
            stock.ratios.year(2016).get("Gross Profit Margin"),
        ], "pct"],
        'Operating Profit Margin': [[
            stock.ratios.quarter(2020, "Q2").get("Operating Profit Margin"),
            stock.ratios.quarter(2020, "Q1").get("Operating Profit Margin"),
            stock.ratios.year(2019).get("Operating Profit Margin"),
            stock.ratios.year(2018).get("Operating Profit Margin"),
            stock.ratios.year(2017).get("Operating Profit Margin"),
            stock.ratios.year(2016).get("Operating Profit Margin"),
        ], "pct"],
        'Net Profit Margin': [[
            stock.ratios.quarter(2020, "Q2").get("Net Profit Margin"),
            stock.ratios.quarter(2020, "Q1").get("Net Profit Margin"),
            stock.ratios.year(2019)["Net Profit Margin"],
            stock.ratios.year(2018)["Net Profit Margin"],
            stock.ratios.year(2017)["Net Profit Margin"],
            stock.ratios.year(2016)["Net Profit Margin"],
        ], "pct"],
        'Return on Assets': [[
            stock.ratios.quarter(2020, "Q2").get("Return on Assets"),
            stock.ratios.quarter(2020, "Q1").get("Return on Assets"),
            stock.ratios.year(2019).get("Return on Assets"),
            stock.ratios.year(2018).get("Return on Assets"),
            stock.ratios.year(2017).get("Return on Assets"),
            stock.ratios.year(2016).get("Return on Assets"),
        ], "pct"],
        'Return on Equity': [[
            stock.ratios.quarter(2020, "Q2").get("Return on Equity"),
            stock.ratios.quarter(2020, "Q1").get("Return on Equity"),
            stock.ratios.year(2019).get("Return on Equity"),
            stock.ratios.year(2018).get("Return on Equity"),
            stock.ratios.year(2017).get("Return on Equity"),
            stock.ratios.year(2016).get("Return on Equity"),
        ], "pct"],
        'Debt Equity Ratio': [[
            stock.ratios.quarter(2020, "Q2").get("Debt Equity Ratio"),
            stock.ratios.quarter(2020, "Q1").get("Debt Equity Ratio"),
            stock.ratios.year(2019).get("Debt Equity Ratio"),
            stock.ratios.year(2018).get("Debt Equity Ratio"),
            stock.ratios.year(2017).get("Debt Equity Ratio"),
            stock.ratios.year(2016).get("Debt Equity Ratio"),
        ], "ratio"],
        'Interest Coverage': [[
            stock.ratios.quarter(2020, "Q2").get("Interest Coverage"),
            stock.ratios.quarter(2020, "Q1").get("Interest Coverage"),
            stock.ratios.year(2019).get("Interest Coverage"),
            stock.ratios.year(2018).get("Interest Coverage"),
            stock.ratios.year(2017).get("Interest Coverage"),
            stock.ratios.year(2016).get("Interest Coverage"),
        ], "ratio"],
        'Price To Book Ratio': [[
            stock.ratios.quarter(2020, "Q2").get("Price To Book Ratio"),
            stock.ratios.quarter(2020, "Q1").get("Price To Book Ratio"),
            stock.ratios.year(2019).get("Price To Book Ratio"),
            stock.ratios.year(2018).get("Price To Book Ratio"),
            stock.ratios.year(2017).get("Price To Book Ratio"),
            stock.ratios.year(2016).get("Price To Book Ratio"),
        ], "ratio"],
        'Current Ratio': [[
            stock.ratios.quarter(2020, "Q2").get("Current Ratio"),
            stock.ratios.quarter(2020, "Q1").get("Current Ratio"),
            stock.ratios.year(2019).get("Current Ratio"),
            stock.ratios.year(2018).get("Current Ratio"),
            stock.ratios.year(2017).get("Current Ratio"),
            stock.ratios.year(2016).get("Current Ratio"),
        ], "ratio"],
        'Free Cash Flow Ratio': [[
            stock.metrics.freeCashFlowRatio().quarter(2020, "Q2"),
            stock.metrics.freeCashFlowRatio().quarter(2020, "Q1"),
            stock.metrics.freeCashFlowRatio().year(2019),
            stock.metrics.freeCashFlowRatio().year(2018),
            stock.metrics.freeCashFlowRatio().year(2017),
            stock.metrics.freeCashFlowRatio().year(2016),
        ], "ratio"],
    }
